/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NewListingRouteImport } from './routes/new-listing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimSlugRouteImport } from './routes/claim.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksIngestTickRouteImport } from './routes/api/public/hooks/ingest-tick'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewListingRoute = NewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimSlugRoute = ClaimSlugRouteImport.update({
  id: '/claim/$slug',
  path: '/claim/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/admin/ingest',
  path: '/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestTickRoute =
  ApiPublicHooksIngestTickRouteImport.update({
    id: '/api/public/hooks/ingest-tick',
    path: '/api/public/hooks/ingest-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/new-listing': typeof NewListingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/api/public/hooks/ingest-tick': typeof ApiPublicHooksIngestTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/new-listing': typeof NewListingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/api/public/hooks/ingest-tick': typeof ApiPublicHooksIngestTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/new-listing': typeof NewListingRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/api/public/hooks/ingest-tick': typeof ApiPublicHooksIngestTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/new-listing'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/ingest'
    | '/admin/roles'
    | '/api/geocode'
    | '/business/$slug'
    | '/checkout/return'
    | '/claim/$slug'
    | '/api/public/hooks/ingest-tick'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/new-listing'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/ingest'
    | '/admin/roles'
    | '/api/geocode'
    | '/business/$slug'
    | '/checkout/return'
    | '/claim/$slug'
    | '/api/public/hooks/ingest-tick'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/new-listing'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/ingest'
    | '/admin/roles'
    | '/api/geocode'
    | '/business/$slug'
    | '/checkout/return'
    | '/claim/$slug'
    | '/api/public/hooks/ingest-tick'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  NewListingRoute: typeof NewListingRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminIngestRoute: typeof AdminIngestRoute
  AdminRolesRoute: typeof AdminRolesRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ClaimSlugRoute: typeof ClaimSlugRoute
  ApiPublicHooksIngestTickRoute: typeof ApiPublicHooksIngestTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-listing': {
      id: '/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof NewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$slug': {
      id: '/claim/$slug'
      path: '/claim/$slug'
      fullPath: '/claim/$slug'
      preLoaderRoute: typeof ClaimSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-tick': {
      id: '/api/public/hooks/ingest-tick'
      path: '/api/public/hooks/ingest-tick'
      fullPath: '/api/public/hooks/ingest-tick'
      preLoaderRoute: typeof ApiPublicHooksIngestTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  NewListingRoute: NewListingRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminIngestRoute: AdminIngestRoute,
  AdminRolesRoute: AdminRolesRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ClaimSlugRoute: ClaimSlugRoute,
  ApiPublicHooksIngestTickRoute: ApiPublicHooksIngestTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
