/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewListingRouteImport } from './routes/new-listing'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'

const NewListingRoute = NewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/new-listing': typeof NewListingRoute
  '/business/$slug': typeof BusinessSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/new-listing': typeof NewListingRoute
  '/business/$slug': typeof BusinessSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/new-listing': typeof NewListingRoute
  '/business/$slug': typeof BusinessSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/browse' | '/new-listing' | '/business/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/browse' | '/new-listing' | '/business/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/new-listing'
    | '/business/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  NewListingRoute: typeof NewListingRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-listing': {
      id: '/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof NewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  NewListingRoute: NewListingRoute,
  BusinessSlugRoute: BusinessSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
