CREATE TABLE public.reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), business_id uuid NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE, user_id uuid NOT NULL, rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (business_id, user_id));
CREATE INDEX idx_reviews_business ON public.reviews(business_id);
CREATE INDEX idx_reviews_user ON public.reviews(user_id);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Reviews viewable by all" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users can write own reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own reviews" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users or admins can delete reviews" ON public.reviews FOR DELETE USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER trg_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TABLE public.review_photos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), review_id uuid NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE, storage_path text NOT NULL, sort_order int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_review_photos_review ON public.review_photos(review_id);
ALTER TABLE public.review_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Review photos viewable by all" ON public.review_photos FOR SELECT USING (true);
CREATE POLICY "Owners can insert review photos" ON public.review_photos FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.reviews r WHERE r.id = review_id AND r.user_id = auth.uid()));
CREATE POLICY "Owners can delete review photos" ON public.review_photos FOR DELETE USING (EXISTS (SELECT 1 FROM public.reviews r WHERE r.id = review_id AND r.user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'));
CREATE OR REPLACE FUNCTION public.enforce_review_photo_cap() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$ BEGIN IF (SELECT count(*) FROM public.review_photos WHERE review_id = NEW.review_id) >= 4 THEN RAISE EXCEPTION 'Photo limit reached (4 per review on free tier)'; END IF; RETURN NEW; END; $fn$;
CREATE TRIGGER trg_review_photo_cap BEFORE INSERT ON public.review_photos FOR EACH ROW EXECUTE FUNCTION public.enforce_review_photo_cap();
INSERT INTO storage.buckets (id, name, public) VALUES ('review-photos', 'review-photos', true) ON CONFLICT (id) DO NOTHING;
CREATE POLICY "Review photos public read" ON storage.objects FOR SELECT USING (bucket_id = 'review-photos');
CREATE POLICY "Users upload own review photos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'review-photos' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Users delete own review photos" ON storage.objects FOR DELETE USING (bucket_id = 'review-photos' AND auth.uid()::text = (storage.foldername(name))[1]);