// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getSessionDeduped } from './session-cache'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Uses getSessionDeduped() rather than calling supabase.auth.getSession()
// directly — see session-cache.ts. Root-cause fix for a real, confirmed
// permanent hang: a page firing several serverFn calls on mount (each
// independently calling this middleware) triggered concurrent
// getSession() calls that deadlocked via Supabase JS's internal
// navigator.locks session-refresh lock.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await getSessionDeduped()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
